name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - run: yarn install --frozen-lockfile

      - run: yarn nx run-many -t lint test build

      - run: yarn nx fix-ci
        if: always()

  deploy:
    needs: main
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env:
      VACATION_PAY_REMOTE_URL: ${{ secrets.VACATION_PAY_REMOTE_URL }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - run: yarn install --frozen-lockfile

      - name: Build applications
        run: |
          yarn nx build host --configuration=production
          yarn nx build vacationPay --configuration=production

      - name: List build output
        run: ls -la ./dist/apps/

      - name: Setup SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Deploy to Timeweb server
        run: |
          # Create remote directories if they don't exist
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@45.144.221.205 "mkdir -p /var/www/host /var/www/vacationPay"

          # Deploy host application
          scp -o StrictHostKeyChecking=no -r ./dist/apps/host/* ${{ secrets.SSH_USER }}@45.144.221.205:/var/www/host/

          # Deploy vacationPay application
          scp -o StrictHostKeyChecking=no -r ./dist/apps/vacationPay/* ${{ secrets.SSH_USER }}@45.144.221.205:/var/www/vacationPay/

          # Set proper permissions
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@45.144.221.205 "chmod -R 755 /var/www/host /var/www/vacationPay"

      - name: Restart web server (if needed)
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@45.144.221.205 "sudo systemctl reload nginx || sudo service nginx reload" || true
